name: Sixth Workflow Using GitHub Actions

run-name: >+ 
          Sixth workflow 
          ${{ github.actor  }} has triggered this workflow \
          using ${{ github.event_name }} event \
          on branch ${{ github.ref  }} of ${{github.repository}} repo.
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out to the repository
        uses: actions/checkout@v4
      - name: List all the files in the repo branch
        run: ls -la
      - name: Printing the contents of a file
        run: cat firstfile.txt
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    if: always()
    steps:
      - name: Send notification about the cicd status
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: ${{secrets.SMTP_HOST}}
          server_port: 587
          secure: false
          username: ${{secrets.SMTP_USERNAME}}
          password: ${{secrets.SMTP_PASSWORD}}
          subject: Github Actions job result
          to: ${{vars.MAIL_TO_LIST}}
          from: sajidali - GitHub Action
          body: Build job of ${{github.repository}} completed with result status of ${{needs.first-job.result}}
